In [1]:
##KNN Supervized Classifier to predict the type of Flower in Iris Data set

In [12]:
# Import Libraries
from scipy.stats import zscore
import seaborn as sns
import matplotlib.pyplot as plt
# load the iris dataset
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics


In [13]:
# Load the sample data set
iris = load_iris()
# store the X-feature matrix and y-response vector
X = iris.data
y = iris.target

print(X[:10])



[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [14]:
### This shows how the iris data set is organized

In [15]:
import pandas as pd 
import numpy as np

df = pd.DataFrame(data=np.c_[iris['data'], iris['target']],
                  columns= iris['feature_names'] + ['target']).astype({'target': int}) \
       .assign(species=lambda x: x['target'].map(dict(enumerate(iris['target_names']))))

df.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target species  
0       0  setosa  
1       0  setosa  
2       0  setosa  
3       0  setosa  
4       0  setosa

In [16]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn import svm


# splitting X and y into training and testing data sets in 70:30
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)


pipeline_knn=Pipeline([('scalar1',StandardScaler()),
                     ('pca1',PCA(n_components=2)),
                     ('knn_classifier',KNeighborsClassifier())])

pipeline_svm = Pipeline([('scalar2', StandardScaler()),
                      ('pca2', PCA(n_components=2)),
                      ('clf', svm.SVC())])

pipelines = [pipeline_svm, pipeline_knn]

pipe_dict = {0: 'Support Vector Machine',1:'K Nearest Neighbor'}

for pipe in pipelines:
  pipe.fit(X_train, y_train)
for i,model in enumerate(pipelines):
    print("{} Test Accuracy:{}".format(pipe_dict[i],model.score(X_test,y_test)))

Support Vector Machine Test Accuracy:0.9333333333333333
K Nearest Neighbor Test Accuracy:0.8888888888888888
